pipeline {
    agent any
    tools {
        maven "maven"
        jdk "JDK"
    }
    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
        stage('Build') {
            steps {
                dir("var/lib/jenkins/workspace/pipelinecheck") {
                sh 'mvn -B -DskipTests clean package'
                }
            }
       }
    }
}
