pipeline {
    agent any
    tools {
        maven "maven"
        jdk "JDK"
    }
    stages {
        stage('WorkSpace Cleanup')
                {
                    steps {
        				cleanWs()
        			}
                }
        stage('Build') {
            steps {
                dir('demo'){
                sh 'mvn -B -DskipTests clean package'
                }
            }
       }
        stage('Test') {
            steps {
                dir('demo'){
                sh 'mvn test'
                }
            }
       }
        stage('Install') {
            steps {
                dir('demo'){
                sh 'mvn -B -DskipTests clean install'
                }
            }
       }
    }
}
